mysqld:
 image: mysql
 environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
 volumes:
   - ./suma:/suma
 restart: always
app:
 image: suma
 ports:
   - "80:80"
 links:
   - mysqld:DB
 volumes:
   - ./suma:/vagrant/suma
   - ./configs:/vagrant/configs
   - ./Config_Softlinks.sh:/vagrant/Config_Softlinks.sh
   - ./postfix.sh:/vagrant/postfix.sh
 restart: always
