# Copy this file to a new file `config.yaml`.
#
# You must modify the following:
#
#    production:
#        sumaserver:
#            db:
#                host: 172.17.0.2
#                dbname: suma mysql database name
#                user: suma mysql **application** account name
#                pword: suma mysql **application** account password
#                port: mysql port number
#            log:
#                path: path to log directory
#                name: sumaserver.log
#
#  * Be sure that the log directory specified in `sumaserver:log:path`
#  both exists and is **writable by the web server**.

production:
    sumaserver:
        db:
            host: 172.17.0.2
            platform: Pdo_Mysql
            dbname: suma
            user: suma
            pword: 12345
            port: 3306
        log:
            path: /vagrant/suma/sumalogs/
            name: sumaserver.log
        admin:
            user: sumaadmin
            pass: sumaadmin
    queryserver:
        db:
            limit: 10000

development:
    _extends: production
    sumaserver:
        db:
            dbname: sumadev
        log:
            path:
